"""Feature engineering."""

from morpheus.features.indicators import (
    OHLCV,
    sma,
    ema,
    rsi,
    atr,
    atr_percent,
    momentum,
    rate_of_change,
    vwap,
    volume_sma,
    relative_volume,
    price_vs_sma,
    bollinger_bands,
    macd,
    stochastic,
)
from morpheus.features.rolling_stats import (
    realized_volatility,
    returns_from_closes,
    log_returns_from_closes,
    rolling_mean,
    rolling_std,
    z_score,
    price_z_score,
    mean_reversion_score,
    momentum_score,
    trend_strength,
    trend_direction,
    volatility_percentile,
    high_low_range,
    price_position_in_range,
    consecutive_direction,
)
from morpheus.features.feature_engine import (
    FEATURE_SCHEMA_VERSION,
    MIN_BARS_REQUIRED,
    FeatureContext,
    FeatureEngine,
    create_feature_context,
    candle_to_ohlcv,
)

__all__ = [
    # Indicators
    "OHLCV",
    "sma",
    "ema",
    "rsi",
    "atr",
    "atr_percent",
    "momentum",
    "rate_of_change",
    "vwap",
    "volume_sma",
    "relative_volume",
    "price_vs_sma",
    "bollinger_bands",
    "macd",
    "stochastic",
    # Rolling stats
    "realized_volatility",
    "returns_from_closes",
    "log_returns_from_closes",
    "rolling_mean",
    "rolling_std",
    "z_score",
    "price_z_score",
    "mean_reversion_score",
    "momentum_score",
    "trend_strength",
    "trend_direction",
    "volatility_percentile",
    "high_low_range",
    "price_position_in_range",
    "consecutive_direction",
    # Feature engine
    "FEATURE_SCHEMA_VERSION",
    "MIN_BARS_REQUIRED",
    "FeatureContext",
    "FeatureEngine",
    "create_feature_context",
    "candle_to_ohlcv",
]
