"""Execution guard and order routing."""

from morpheus.execution.base import (
    EXECUTION_SCHEMA_VERSION,
    TradingMode,
    ExecutionDecision,
    BlockReason,
    OrderType,
    OrderSide,
    OrderStatus,
    generate_order_intent_id,
    generate_client_order_id,
    ExecutionCheck,
    OrderRequest,
    OrderResult,
    ExecutionConfig,
    ExecutionGuard,
    OrderRouter,
    BrokerAdapter,
    FSM_TRANSITION_MAP,
)
from morpheus.execution.guards import (
    GuardConfig,
    StandardExecutionGuard,
    PermissiveExecutionGuard,
    StrictExecutionGuard,
    create_standard_guard,
    create_permissive_guard,
    create_strict_guard,
    ConfirmationRequest,
    ConfirmationResult,
    ConfirmationGuardConfig,
    ConfirmationGuard,
    create_confirmation_guard,
)
from morpheus.execution.router import (
    RouterConfig,
    StandardOrderRouter,
    MarketOrderRouter,
    LimitOrderRouter,
    create_standard_router,
    create_market_router,
    create_limit_router,
)
from morpheus.execution.schwab_adapter import (
    SchwabOrderError,
    SchwabBrokerAdapter,
    PaperBrokerAdapter,
    create_schwab_adapter,
    create_paper_adapter,
)
from morpheus.execution.paper_position_manager import (
    ExitReason,
    ExitPlan,
    ExitConfig,
    PaperPosition,
    PaperPositionManager,
)

__all__ = [
    # Base
    "EXECUTION_SCHEMA_VERSION",
    "TradingMode",
    "ExecutionDecision",
    "BlockReason",
    "OrderType",
    "OrderSide",
    "OrderStatus",
    "generate_order_intent_id",
    "generate_client_order_id",
    "ExecutionCheck",
    "OrderRequest",
    "OrderResult",
    "ExecutionConfig",
    "ExecutionGuard",
    "OrderRouter",
    "BrokerAdapter",
    "FSM_TRANSITION_MAP",
    # Guards
    "GuardConfig",
    "StandardExecutionGuard",
    "PermissiveExecutionGuard",
    "StrictExecutionGuard",
    "create_standard_guard",
    "create_permissive_guard",
    "create_strict_guard",
    # Confirmation Guard
    "ConfirmationRequest",
    "ConfirmationResult",
    "ConfirmationGuardConfig",
    "ConfirmationGuard",
    "create_confirmation_guard",
    # Router
    "RouterConfig",
    "StandardOrderRouter",
    "MarketOrderRouter",
    "LimitOrderRouter",
    "create_standard_router",
    "create_market_router",
    "create_limit_router",
    # Adapters
    "SchwabOrderError",
    "SchwabBrokerAdapter",
    "PaperBrokerAdapter",
    "create_schwab_adapter",
    "create_paper_adapter",
    # Exit Management v1
    "ExitReason",
    "ExitPlan",
    "ExitConfig",
    "PaperPosition",
    "PaperPositionManager",
]
